apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-for-customdomain-http
spec:
  rules:
    - host: destinhebert.com
      http:
        paths:
          - path: /
            backend:
              serviceName: tcluster
              servicePort: 31609
